from dataclasses import dataclass
from pathlib import Path

from docx import Document

from loro.artifacts.common import ArtifactResult, ensure_output_dir, slugify, title_from_prompt


@dataclass(frozen=True)
class DocumentDraft:
    title: str
    markdown: str


def create_markdown_document(title: str, body: str) -> DocumentDraft:
    return DocumentDraft(title=title, markdown=f"# {title}\n\n{body.strip()}\n")


def create_document_artifact(prompt: str, output_dir: Path) -> ArtifactResult:
    title = title_from_prompt(prompt, "Loro Document")
    slug = slugify(title, "document")
    output_dir = ensure_output_dir(output_dir)
    markdown_path = output_dir / f"{slug}.md"
    docx_path = output_dir / f"{slug}.docx"

    body = (
        "## Purpose\n\n"
        f"{prompt.strip()}\n\n"
        "## Draft\n\n"
        "This document was generated by Loro's deterministic MVP artifact engine. "
        "Future model integration will expand this draft with richer context, memory retrieval, "
        "and governed enterprise data citations.\n\n"
        "## Assumptions\n\n"
        "- The user approved the prompt as source context.\n"
        "- No restricted data was embedded by the scaffolded generator.\n\n"
        "## Next Steps\n\n"
        "- Review the draft for accuracy.\n"
        "- Add organization-specific template requirements.\n"
        "- Confirm whether any content should be promoted to local or shared memory.\n"
    )
    draft = create_markdown_document(title, body)
    markdown_path.write_text(draft.markdown, encoding="utf-8")

    document = Document()
    document.add_heading(title, level=1)
    for section in body.split("\n\n"):
        if section.startswith("## "):
            document.add_heading(section.removeprefix("## ").strip(), level=2)
        elif section.strip():
            document.add_paragraph(section.strip())
    document.save(docx_path)

    return ArtifactResult(
        title=title,
        kind="document",
        paths=[markdown_path, docx_path],
        summary=f"Created document artifacts: {markdown_path} and {docx_path}",
    )
