from dataclasses import dataclass
from pathlib import Path

from pptx import Presentation

from loro.artifacts.common import (
    ArtifactResult,
    ensure_output_dir,
    title_from_prompt,
    unique_slug,
)


@dataclass(frozen=True)
class Slide:
    title: str
    bullets: list[str]


@dataclass(frozen=True)
class PresentationOutline:
    title: str
    slides: list[Slide]


def create_presentation_artifact(
    prompt: str, output_dir: Path, *, outline: PresentationOutline | None = None
) -> ArtifactResult:
    title = outline.title if outline else title_from_prompt(prompt, "Loro Presentation")
    slug = unique_slug(title, "presentation")
    output_dir = ensure_output_dir(output_dir)
    outline_path = output_dir / f"{slug}-outline.md"
    pptx_path = output_dir / f"{slug}.pptx"

    outline = outline or PresentationOutline(
        title=title,
        slides=[
            Slide(
                title="Context",
                bullets=[prompt.strip(), "Audience and goals should be reviewed."],
            ),
            Slide(
                title="Key Points",
                bullets=[
                    "Summarize the current state.",
                    "Call out decisions, risks, and opportunities.",
                    "Tie recommendations to enterprise memory and governed data when available.",
                ],
            ),
            Slide(
                title="Next Steps",
                bullets=[
                    "Validate facts and metrics.",
                    "Apply organization template and branding.",
                    "Confirm follow-up owners.",
                ],
            ),
        ],
    )
    outline_sections = [f"# {outline.title}"]
    outline_sections.extend(
        f"## {slide.title}\n" + "\n".join(f"- {item}" for item in slide.bullets)
        for slide in outline.slides
    )
    outline_path.write_text("\n\n".join(outline_sections) + "\n", encoding="utf-8")

    deck = Presentation()
    title_slide = deck.slides.add_slide(deck.slide_layouts[0])
    title_slide.shapes.title.text = title
    title_slide.placeholders[1].text = "Generated by Loro"
    for slide in outline.slides:
        ppt_slide = deck.slides.add_slide(deck.slide_layouts[1])
        ppt_slide.shapes.title.text = slide.title
        body = ppt_slide.shapes.placeholders[1].text_frame
        body.clear()
        for index, bullet in enumerate(slide.bullets):
            paragraph = body.paragraphs[0] if index == 0 else body.add_paragraph()
            paragraph.text = bullet
            paragraph.level = 0
    deck.save(pptx_path)

    return ArtifactResult(
        title=title,
        kind="presentation",
        paths=[outline_path, pptx_path],
        summary=f"Created presentation artifacts: {outline_path} and {pptx_path}",
    )
